---
- name: Tmux | Install tmux
  action: apt pkg=tmux state=latest

- name: Tmux | Add .tmux.conf for each user
  with_items: users
  template: src=tmux.conf.j2
            dest=~{{ item.username }}/.tmux.conf
            owner={{ item.username }}
            group={{ item.username }}
