---
- name: Tmux | Install tmux
  action: apt pkg=tmux state=latest

- name: Tmux | Add tmux.conf
  template: src=tmux.conf.j2
            dest=/etc/tmux.conf
            owner=root
            group=root
